### ISSUE TITLE
Transfer project into Asciidoctor organization

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-fb2#20]
Subj, @mojavelinux showed some interest in this project.

I'm not sure how the procedure works.

GitHub has this:

![image](https://user-images.githubusercontent.com/92637/100273785-64dc4f80-2f6e-11eb-9599-4eb043710e55.png)

Given that it says "Transferring may be delayed until the new owner approves the transfer.", I possibly do not actually need to have a permission to create repositories under Asciidoctor organization.

I also need to add someone as an owner on rubygems.org:

![image](https://user-images.githubusercontent.com/92637/100274134-f8ae1b80-2f6e-11eb-95f3-a40943812d30.png)

**Comment by slonopotamus** [comment]
Possible issue: asciidoctor-fb2 is not currently using Dan-approved Rubocop rules and instead uses default Rubocop settings (while agressively suppressing annoying ones like `Metrics/AbcSize`). I mostly did this because I was too lazy to write Rubocop config and have no objections against setting a different set of rules. Having *some* set of code style rules is much more important, exact rules are not for me.

**Comment by mojavelinux** [comment]
I think repository transfers are now enabled. I will watch for the transfer to happen in case I need to approve something. GitHub is constantly change the process, so each time it requires different steps.

Please add my username, mojavelinux, as an owner of the gem on RubyGems.org. I only use this permission for the purpose of administering the ownership in the event you cannot (basically, so we don't lose access to the gem).

Since this is an extended converter, I'm not concerned about the code style. As long as you have a code style, that's what matters. This is a choice I leave up to each project.

Although the rules are not well publicized, the criteria for project transfers to the asciidoctor organization are at least:

* functionality that is general useful
* a test suite
* a code linter
* a CI job to run tests
* an automated release process
* a compatible license

This repository satisfies all of these criteria.

**Comment by slonopotamus** [comment]
Transfer button errored with:

> You don’t have the permission to create public repositories on **asciidoctor**

**Comment by mojavelinux** [comment]
Okay, then it's the other check box ;) Try again.

**Comment by slonopotamus** [comment]
Yay, it worked! Though now I don't have permissions in repo and not sure if RuubyGems API key is still in GH-Actions secrets.

**Comment by mojavelinux** [comment]
Yep, that's always a follow-up task I have to do. I'm working on it.

**Comment by mojavelinux** [comment]
You should now have access as a member of the asciidoctor-fb2 team. You can manage the members of this team to control who has admin access to the repo. You can also add individuals.

**Comment by slonopotamus** [comment]
Confirming, seems like everything is up and running. And API key is still there.
